version: "3.9"
services:
  node-app:
    build: .
    image: node-app-image
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mySecretPassword
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - node-app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
volumes:
  mongo-db: